name: PHP Code Sniffer

on: pull_request

jobs:
  phpcs:
    name: Drupal coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, dom, gd, pdo_mysql
          tools: composer:v2.3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ansi --no-interaction --verbose

      - id: files
        uses: masesgroup/retrieve-changed-files@v3
        continue-on-error: true

      - name: List changed files
        run: |
          echo "Files added or modified in this PR:"
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "${changed_file}"
          done
          echo ""

      - name: Check coding standards
        run: |
          vendor/bin/phpcs ${{ steps.files.outputs.added_modified }}
